apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: airbyte
  namespace: argocd
spec:
  project: data-stack
  source:
    repoURL: https://airbytehq.github.io/helm-charts
    chart: airbyte
    targetRevision: 1.7.0
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: data-stack
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
